var supportedLanguages = {
"en": "English",
"zh": "中文 (Chinese)",
"zh-TW": "繁體中文 (Chinese Traditional)",
"es": "Español (Spanish)",
"es-MX": "Español Mexicano (Mexican Spanish)",
"hi": "हिन्दी (Hindi)",
"ar": "العربية (Arabic)",
"pt": "Português (Portuguese)",
"pt-PT": "Português de Portugal (Portugal Portuguese)",
"ru": "Русский (Russian)",
"fr": "Français (French)",
"fr-CA": "Français Canadien (Canadian French)",
"de": "Deutsch (German)",
"ja": "日本語 (Japanese)",
"ur": "اردو (Urdu)",
"id": "Bahasa Indonesia (Indonesian)",
"bn": "বাংলা (Bengali)",
"vi": "Tiếng Việt (Vietnamese)",
"ko": "한국어 (Korean)",
"it": "Italiano (Italian)",
"tr": "Türkçe (Turkish)",
"pl": "Polski (Polish)",
"fa": "فارسی (Persian)",
"uk": "Українська (Ukrainian)",
"nl": "Nederlands (Dutch)",
"th": "ไทย (Thai)",
"ms": "Bahasa Melayu (Malay)",
"el": "Ελληνικά (Greek)",
"hu": "Magyar (Hungarian)",
"sv": "Svenska (Swedish)",
"cs": "Čeština (Czech)",
"ro": "Română (Romanian)",
"az": "Azərbaycanca (Azerbaijani)",
"ta": "தமிழ் (Tamil)",
"ml": "മലയാളം (Malayalam)",
"gu": "ગુજરાતી (Gujarati)",
"kn": "ಕನ್ನಡ (Kannada)",
"te": "తెలుగు (Telugu)",
"mr": "मराठी (Marathi)",
"pa": "ਪੰਜਾਬੀ (Punjabi)",
"fi": "Suomi (Finnish)",
"hy": "Հայերեն (Armenian)",
"lt": "Lietuvių (Lithuanian)",
"lv": "Latviešu (Latvian)",
"sl": "Slovenščina (Slovenian)",
"no": "Norsk (Norwegian)",
"bg": "Български (Bulgarian)",
"sr": "Српски (Serbian)",
"hr": "Hrvatski (Croatian)",
"et": "Eesti (Estonian)",
"ka": "ქართული (Georgian)",
"bs": "Bosanski (Bosnian)",
"is": "Íslenska (Icelandic)",
"ps": "پښتو (Pashto)",
"am": "አማርኛ (Amharic)",
"cy": "Cymraeg (Welsh)",
"kk": "Қазақ (Kazakh)",
"sq": "Shqip (Albanian)",
"so": "Soomaali (Somali)",
"uz": "O‘zbek (Uzbek)",
"ht": "Kreyòl Ayisyen (Haitian Creole)",
"si": "සිංහල (Sinhala)",
"mn": "Монгол (Mongolian)",
"ga": "Gaeilge (Irish)",
"af": "Afrikaans",
"ha": "Hausa",
"tl": "Tagalog (Filipino)",
"mt": "Malti (Maltese)",
"mk": "Македонски (Macedonian)",
"sw": "Kiswahili (Swahili)",
"ca": "Català (Catalan)",
"da": "Dansk (Danish)",
"sk": "Slovenčina (Slovak)",
"he": "עברית (Hebrew)",
"fa-AF": "دری (Dari)"
};